some refactor done(Extract Method)
Star-Academy/Summer1401-SE-Team06 pull request #1
Opened 2022-07-19 12:54 UTC by ali-bonaftizadeh

2022-07-20 07:06 UTC, mojo-izadi commented on Phase01/src/Main.java
> +                    necessaries.retainAll(invertedIndexMap.get(s));
good implementation!

2022-07-20 08:13 UTC, mojo-izadi reviewed
line 27 pass object instead of long parameter list
'searchInDocs' method is very long!!!
each class should only do one thing and Main class should only call other classes ( methods like processInputAndSearch should be in other classes (You can even make a new class for them)
in line 77 try iterating on the files in the folder directly (using foreach) instead of using the file names directly so your code still works even if the files are renamed

2022-07-21 05:04 UTC, amirarab888 requested changes

2022-07-21 05:04 UTC, amirarab888 commented on Phase01/src/AppController.java
> +    private static InvertedIndex preprocess() {
به کلاس دیگری منتقل بشه

2022-07-21 05:04 UTC, amirarab888 commented on Phase01/src/AppController.java
> +    private static Set<Integer> processInputAndSearch(String[] input, InvertedIndex invertedIndex) {
به کلاس دیگری منتقل بشه

2022-07-21 05:04 UTC, amirarab888 commented on Phase01/src/AppController.java
> +        SearchInDocs searchInDocs = new SearchInDocs(invertedIndex.getInvertedIndex());
هیچ شی در شی دیگری, instantiate نشود, همه چی در بالاترین لایه که در برنامه شما main است, new شود و به لایه های پایین پاس داده شود, شاید بگید که باعث میشه تعداد آرگومان های ورودی بعضی توابع بسیار زیاد میشود, ولی در آینده با مفهوم DI این مشکل شما حل میشود.

2022-07-21 05:04 UTC, amirarab888 commented on Phase01/src/AppController.java
> +        SearchInDocs searchInDocs = new SearchInDocs(invertedIndex.getInvertedIndex());
مگر ساختار داده های عادی مثل arrayList که اشکالی نداره درون هر کلاسی instantiate شوند.

2022-07-21 05:04 UTC, amirarab888 commented on Phase01/src/FileReader.java
> +            }
try catch 
اصلا پترن مناسبی نیست مخصوصا وقتی اکسپشن را کچ کرده و اکسپشن دیگری پرتاب کنید که کاستوم نباشد و با مفهوم خطا نیز سازگار نباشد(کاستوم یعنی این که اکسپشن مناسبی با متن خطای مناسب فرزند اینترفیس اکسپشن بسازید), به راه دیگری فکر کنید, مانند این که یک کلاس مدل result بسازید و در آن بولینی داشته باشید که اشاره به خطای IO داشته باشید و در این جا آن را ریترن کنید

2022-07-21 05:04 UTC, amirarab888 commented on Phase01/src/FileReader.java
> +            }
ضمنا باید درون حلقه for را extract method کنید تا از nested شدن جلوگیری کند

2022-07-21 05:04 UTC, amirarab888 commented on Phase01/src/SearchInDocs.java
> +                avoids.addAll(invertedIndexMap.get(s));
همیشه curly brace بدنه شرط را بگذارید, چون در کد هایی که چندین نویسنده دارد, احتمال ایجاد باگ زیاد میشود.

2022-07-23 08:01 UTC, RAAvenger reviewed
سلام بچه‌ها خسته نباشید
پوشه out رو حتما حتما به gitignore اضافه کنید و با کامند git rm -r --cached از گیتتون پاکش کنید

2022-07-23 08:01 UTC, RAAvenger commented on Phase01/src/AppController.java
> +        MakeInvertedIndex makeInvertedIndex = new MakeInvertedIndex(invertedIndex, fileReader);
از اونجایی که invertedIndex بیشتر یه داده ساختار هست منطقی نیست که توی MakeInvertedIndex ساخته بشه؟

2022-07-23 08:01 UTC, RAAvenger commented on Phase01/src/FileReader.java
> +        docNameToContent.put(Integer.parseInt(fileName), content);
اینجا پیشفرض رو این گرفتین که اسم فایل عددیه
همچین پیشفرضی صحیحه؟

2022-07-23 08:01 UTC, RAAvenger commented on Phase01/src/MakeInvertedIndex.java
> +public class MakeInvertedIndex {
اسم کلاس یه جوریه، جای MakeInvertedIndex یه چیزی توی مایه‌های InvertedIndexMaker بهتره

2022-07-23 08:01 UTC, RAAvenger commented on Phase01/src/SearchInDocs.java
> +        for (String s : avoided) {
اسم متغییر تک حرفی نذارید

به جز i برای index که اگر از i هم استفاده نکنید خوب میشه

2022-07-23 12:41 UTC, RAAvenger approved these changes

2022-07-23 12:41 UTC, RAAvenger commented on .gitignore
> +/out/
از این سایت هم استفاده کنید
https://www.toptal.com/developers/gitignore

2022-07-23 12:41 UTC, RAAvenger approved these changes

2022-07-23 20:11 UTC, Taha-Alikhani commented
> سلام بچه‌ها خسته نباشید پوشه out رو حتما حتما به gitignore اضافه کنید و با کامند git rm -r --cached از گیتتون پاکش کنید

+ .idea  (IDE-related files and folders)

2022-07-24 13:11 UTC, mojo-izadi approved these changes

2022-07-24 14:29 UTC, amirarab888 approved these changes

2022-07-24 14:29 UTC, amirarab888 commented on Phase01/src/AppController.java
> +            if (s.startsWith("+")) optional.add(s.substring(1));
در این شرایط چون سه تا operation بیشتر نبود, این کار به صرفه است که if , else بذاریم, اما در یک پروژه واقعی آیا ممکن نیست که در تعداد operation ها تفاوت ایجاد شود و ما Open Close Princlple را نقض کنیم؟

2022-07-24 14:29 UTC, amirarab888 commented on Phase01/src/AppController.java
> +            if (s.startsWith("+")) optional.add(s.substring(1));
در نتیجه راه حلی برای این مسئله بیابید و تغییر دهید.

2022-07-24 14:34 UTC, RAAvenger approved these changes

2022-07-25 11:27 UTC, merged