some code refactor applied
Star-Academy/Summer1401-SE-Team06 pull request #2
Opened 2022-07-25 11:57 UTC by ali-bonaftizadeh

2022-07-25 17:40 UTC, Taha-Alikhani requested changes
- FileReader class does more than 1 tasks (reading the files, parsing json)
- Choose a meaningful namespace
- Output class can be optimized further (for example sortedStudents is calculated 3 times, we just need to calculate it once)
- Output folders (debug, obj, etc.) should be added to .gitignore

2022-07-30 04:32 UTC, amirarab888 requested changes
فایل های اضافی ایگنور بشن

2022-07-30 04:32 UTC, amirarab888 commented on Phase03/project/JsonParser.cs
> +            var student = students.Where(x => x.StudentNumber == (int)item.StudentNumber);
چرا cast کردی؟

2022-07-30 04:32 UTC, amirarab888 commented on Phase03/project/Student.cs
> +    private List<Lesson> Lessons { get; } = new();
لزومی نداره که این جا init بشن

2022-07-30 04:45 UTC, ali-bonaftizadeh commented on Phase03/project/Student.cs
> +    private List<Lesson> Lessons { get; } = new();
خود ide پیشنهاد داد که initialize کنیم، ولی اوکیه پاکش میکنیم.

2022-07-30 04:49 UTC, ali-bonaftizadeh commented on Phase03/project/JsonParser.cs
> +            var student = students.Where(x => x.StudentNumber == (int)item.StudentNumber);
ارور میده اگه کست نکنیم.
![image](https://user-images.githubusercontent.com/79264950/181873293-1f900396-eaaa-471d-8821-82022aecf73b.png)

2022-07-30 10:21 UTC, amirarab888 approved these changes
یه کامنت دیگه گذاشتم اصلاح بشه غیر از اون مورد دیگه ای نیست

2022-07-30 10:21 UTC, amirarab888 commented on Phase03/project/JsonParser.cs
> +            var student = students.Where(x => x.StudentNumber == (int)item.StudentNumber);
باید اون جایی که داری سریالایز میکنی تایپ جنریک تابع رو بهش بدی 
 JsonConvert.DeserializeObject<Student>
که بیاید بر اساس اون کلاسه دیسریالایز کنه

2022-07-30 16:58 UTC, Taha-Alikhani approved these changes

2022-08-01 10:36 UTC, RAAvenger requested changes
سلام
خسته نباشید
فولدرایی مثل idea و bin و  obj روی گیت نیان.

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/JsonParser.cs
> +        dynamic studentsJson = JsonConvert.DeserializeObject(studentsData);
چرا `dynamic`؟

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/JsonParser.cs
> +        return students;
چرا؟
کل این با یه `JsonConvert.DeserializeObject<List<Student>>(studentsData)`  انجام میشه

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/Lesson.cs
>  public class Lesson
جای `class` میتونید از `record` استفاده کنید

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/Output.cs
>  {
کلاس اسم خوبی نداره
https://pspdfkit.com/blog/2018/naming-classes-why-it-matters-how-to-do-it-well/

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/Output.cs
>      public void printTopStudents(List<Student> students)
نامگذاری بر اساس کانونشن #c نیست

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/Output.cs
>          }
کل این رو با linq بزنید

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/ProgramController.cs
> +public class ProgramController
واژه Controller یه چیز معنی داره توی معماری mvc و بهتره ازش استفاده نکنید مگر اینکه توی معماری mvc باشید

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/ProgramController.cs
>                  "https://docs.code-star.ir/assets/files/scores-76885bff66d5238dfd0661c6ac6d74fc.json");
کار جالبی کردید ولی اگر به هر دلیل لینکی که دادید کار نکنه برنامه‌تون مشکل پیدا میکنه
همچنین با این منطق هربار داره فایلا رو از اینترنت میخونه که خیلی بهینه نیست
اگر فایلا رو دانلود کنید و بذارید کنار پروژه بهینه‌تره

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/Student.cs
>  public class Student
این کلاس میتونه record باشه

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/Student.cs
>      public double AverageGrade { get; set; }
برای این getter میتونین توی قسمت get کد محاسبه این مقدار رو داشته باشید

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/Student.cs
>      {
خط14
بجای `Lessons.Select(x => x.Score).Average()` میتونید از  `Lessons.Average(x => x.Score)` استفاده کنید

2022-08-01 10:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
> +using System.Reflection;
کل فولدرای obj از گیت پاک بشن
برای ایجاد گیت ایگنور هم از https://www.toptal.com/developers/gitignore استفاده کنید و اگر سوال داشتید از @amirarab888 بپرسید

2022-08-01 10:36 UTC, RAAvenger commented on Phase03/project/FileReader.cs
>              return wc.DownloadString(url);
توی اسم گذاریا بیشتر دقت کنید

2022-08-02 06:56 UTC, matinmoradi80 commented on Phase03/project/Lesson.cs
>  public class Lesson
برای ویژگی immutable بودن درسته؟

2022-08-02 07:21 UTC, matinmoradi80 commented on Phase03/project/Output.cs
>  {
یکم بیشتر راهنمایی میکنید؟ :))

2022-08-03 17:57 UTC, RAAvenger reviewed
سلام
خسته نباشد
فایلای اضافی (مثل obj و idea) رو پاک کنید

2022-08-03 17:57 UTC, RAAvenger commented on Phase03/project/FileReader.cs
> +        string text = File.ReadAllText(filePath);
از این متغییرای  temp  نگیرید

2022-08-03 17:57 UTC, RAAvenger commented on Phase03/project/JsonParser.cs
> +        dynamic scoresJson = JsonConvert.DeserializeObject(scoresData);
اینجا هم از DeserializeObject با جنریک (<Student>) استفاده کنید

2022-08-03 17:57 UTC, RAAvenger commented on Phase03/project/Lesson.cs
>      public string Name { get; set; }
اگر name در طول عمر کلاس تغییر نمیکنه init بزنید
باقی جاها رو هم بررسی کنید و اصلاح کنید اگر نیاز بود

2022-08-03 17:57 UTC, RAAvenger commented on Phase03/project/OutputPrinter.cs
> +                ("Name: " + student.FirstName + " " + student.LastName + " | Average Score: " + student.AverageGrade));
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

2022-08-03 17:57 UTC, RAAvenger commented on Phase03/project/ProgramRunner.cs
> +        string scrPath = @"C:\Users\User\Summer1401-SE-Team06\Phase03\scoresData.json";
مسیر absolute جالب نیست و برنامه فقط روی یه کامپیوتر خاص کار میکنه
میتونید فایلا رو بذارید کنار برنامه و ازز امکان copy to output استفاده کنید

2022-08-03 17:57 UTC, RAAvenger commented on Phase03/project/Student.cs
> +    private double averageGrade;
کاربرد این چیه؟

2022-08-09 07:40 UTC, matinmoradi80 commented on Phase03/project/Student.cs
> +    private double averageGrade;
backing field هست. 
ولی توی property و تعریف get و set ازش استفاده نکردیم و برای همین فکر کنم بهتر باشه یا field را حذف کنیم یا توی property تغییراتی بدیم. درسته؟

2022-08-11 07:16 UTC, Soltaniant commented on Phase03/project/OutputPrinter.cs
> +    }
Same notes that mentioned in the later phases.

2022-08-12 17:41 UTC, RAAvenger approved these changes
سلام
خسته نباشید

2022-08-13 04:36 UTC, merged