Phase04
Star-Academy/Summer1401-SE-Team06 pull request #3
Opened 2022-07-30 07:25 UTC by ali-bonaftizadeh

2022-07-30 08:22 UTC, KhosroMoeini reviewed
Some failing cases exist but they are not tested.
Hint: Think about some border cases regarding `int`.

2022-07-30 08:22 UTC, KhosroMoeini commented on Phase04/SimpleCalculator.Test/SimpleCalculator.Business.Tests.cs
> +        expected.Should().Be(result);
Testing the `Calculate` function without mocking `IOperator` and `IOperatorProvider` violates Unit-Test principle.
`OperatorProvider` and each `Operator` class should be tested separately.
`Calculator` class should be tested with mocked implementations of the required interfaces.

2022-08-01 10:28 UTC, amirarab888 requested changes

2022-08-01 10:28 UTC, amirarab888 commented on Phase04/SimpleCalculator.Business/Calculator.cs
> +            var @operator = _operatorProvider.GetOperator(operatorType);
ات اول اسم چیه قضیش؟

2022-08-01 10:28 UTC, amirarab888 commented on Phase04/SimpleCalculator.Business/OperatorBusiness/OperatorProvider.cs
> +            return operatorType switch
این روش بر خلاف قاعده open close هست
در مورد factory method design pattern بخونید و اصلاح کنید

2022-08-01 10:28 UTC, amirarab888 commented on Phase04/SimpleCalculator.Test/CalculatorTests.cs
> +        mockedOperatorToAddNumbers.Calculate(Arg.Any<int>(), Arg.Any<int>()).Returns(6);
از arg.is استفاده کنید

2022-08-01 11:36 UTC, ali-bonaftizadeh commented on Phase04/SimpleCalculator.Business/Calculator.cs
> +            var @operator = _operatorProvider.GetOperator(operatorType);
مام نمیدونیم والا :)
 این کدی هست که در اختیارمون دادن تا براش تست بنویسیم.

2022-08-01 11:36 UTC, ali-bonaftizadeh commented on Phase04/SimpleCalculator.Business/OperatorBusiness/OperatorProvider.cs
> +            return operatorType switch
این هم برای همون کد آماده هست ما نزدیمش.

2022-08-01 11:46 UTC, ali-bonaftizadeh commented on Phase04/SimpleCalculator.Test/CalculatorTests.cs
> +        mockedOperatorToAddNumbers.Calculate(Arg.Any<int>(), Arg.Any<int>()).Returns(6);
متوجه نشدم. به چه منظور ازش استفاده کنیم؟ یعنی بگیم فقط ۲ و ۴ رو ورودی بگیره چون خروجی ۶ میده؟

2022-08-03 10:24 UTC, amirarab888 approved these changes

2022-08-03 18:38 UTC, RAAvenger reviewed
سلام
خسته نباشید
تا جای ممکن از var استفاده کنید

2022-08-03 18:38 UTC, RAAvenger commented on Phase04/SimpleCalculator.Test/CalculatorTests.cs
> +        mockedOperatorToAddNumbers.Calculate(Arg.Is<int>(x => x == 4), Arg.Is<int>(x => x == 2)).Returns(6);
عددای 2 و 4 و 6 رو به جای اینکه هاردکد کنید متغییر بگیرید

2022-08-03 18:38 UTC, RAAvenger commented on Phase04/SimpleCalculator.Test/CalculatorTests.cs
> +        IOperator mockedOperatorToAddNumbers = Substitute.For<IOperator>();
var

2022-08-03 18:38 UTC, RAAvenger commented on Phase04/SimpleCalculator.Test/CalculatorTests.cs
> +        var result = calculator.Calculate(4, 2, OperatorEnum.division);
مهمه که همون OperatorEnumای که به calculator داده شده به operatorProvider داده بشه

2022-08-12 17:43 UTC, RAAvenger approved these changes
سلام
خسته نباشید

2022-08-13 04:37 UTC, merged