Phase05
Star-Academy/Summer1401-SE-Team06 pull request #4
Opened 2022-07-30 07:47 UTC by ali-bonaftizadeh

2022-08-02 11:11 UTC, mojo-izadi commented on Phase05/SampleLibrary/SampleLibrary/InvertedIndex.cs
> +    }
try using brackets {} for conditions and for loops to increase readability
the method can also be written in 3 lines by using linQ (you split the string and check the length condition in one line before iterating on it)

2022-08-02 11:11 UTC, mojo-izadi commented on Phase05/SampleLibrary/SampleLibrary/SearchInDocs.cs
> +}
these two methods are doing the exact same thing :)
try using a single method for this

2022-08-02 11:11 UTC, mojo-izadi commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +    {
confusing names
what is the difference between this test and the one before it?
And why does the name end with ReturnTrue when you are asserting certain values not to be true at the end?

2022-08-03 17:40 UTC, nothatcreative5 requested changes

2022-08-03 17:40 UTC, nothatcreative5 commented on Phase05/SampleLibrary/SampleLibrary.Test/SearchEngineTest.cs
> +    public void SearchInDocsTest()
Method name does not follow the naming convention for test methods in C#.

2022-08-03 17:40 UTC, nothatcreative5 commented on Phase05/SampleLibrary/SampleLibrary/FileReader.cs
> +    private readonly string filesDir;
_filesDir

2022-08-03 17:40 UTC, nothatcreative5 commented on Phase05/SampleLibrary/SampleLibrary.Test/SearchEngineTest.cs
> +        searched.Contains("4").Should().NotBe(true);
Use collection.Should().NotContain or collection.Should().Contain.

2022-08-03 17:40 UTC, nothatcreative5 commented on Phase05/SampleLibrary/SampleLibrary.Test/SearchEngineTest.cs
> +        searched.Contains("3").Should().Be(true);
The test can be improved if you initialize the data in a different method, and use InlineData for different test cases.

2022-08-03 17:40 UTC, nothatcreative5 commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +        map["ali"].Contains("1").Should().Be(true);
Use collection.Should().NotContain or collection.Should().Contain.

2022-08-03 17:40 UTC, nothatcreative5 commented on Phase05/SampleLibrary/SampleLibrary.Test/FileReaderTest.cs
> +            ">This wouldn't happen to be the same thing as chiggers, " +
Initializing this long of a string in the method's body looks displeasing.

2022-08-11 09:28 UTC, amirarab888 requested changes

2022-08-11 09:28 UTC, amirarab888 commented on Phase05/SampleLibrary/SampleLibrary.Test/FileReaderTest.cs
> +    {
این جا رسما دارید یه تیکه از سی شارپ رو تست میکنید که بی جهته

2022-08-11 09:28 UTC, amirarab888 commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +        map["ali"].Should().NotContain("2");
این روش دسترسی به دیکشنری باعث ایجاد باگ میشه
در مورد tryGetValue بخونید

2022-08-13 07:57 UTC, amirarab888 approved these changes

2022-08-15 13:36 UTC, RAAvenger requested changes
سلام
خسته نباشید
یه سری ایراد کوچیک هست. اصلاحشون کنید.

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +        if (map.TryGetValue("ali", out value))
میتونید بنویسید
out var value

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +            value.Should().Contain("4");
دوتا مقدار رو بذارید توی یه کالکشن و کالکشنه رو با خروجی مقایسه کنید

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +        if (map.TryGetValue("ali", out value))
جای اسم value هم از actual استفاده کنید

این رو همه جا اعمال کنید

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +        map.ContainsKey("ali").Should().Be(true);
theory

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +        map.ContainsKey("test").Should().NotBe(true);
theory

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +        }
اگر وارد این متده نشیم چی میشه؟

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/InvertedIndexTest.cs
> +    public void InvertedIndex_DocsNotContainingAWord_ReturnsTrue()
همه کامنتای بالا

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/SearchEngineTest.cs
> +        searched.Should().Contain("7");
کالکشن بگیرید و مقایسه کنید

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary.Test/SearchEngineTest.cs
> +        searched.Should().NotContain("6");
مثل قبلی

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary/InvertedIndex.cs
> +        var wordExists = Map.ContainsKey(word);
لازم نیست این مقدار رو توی متغییر بذارید

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary/SearchInDocs.cs
> +        var searchProcessor = SearchProcessor.Instance;
نیاز نیست متغییر بگیرید

2022-08-15 13:36 UTC, RAAvenger commented on Phase05/SampleLibrary/SampleLibrary/SearchInDocs.cs
> +        return result;
نیاز نیست متغییر بگیرید

2022-08-18 13:21 UTC, RAAvenger approved these changes
سلام
خسته نباشید
فایلای اضافی پاک بشن

2022-08-19 21:11 UTC, merged